# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
hosts = {
  "minikube" => "192.168.50.210"
}

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # config.vm.provision "file", source: "docker-compose-Linux-x86_64", destination: "docker-compose-Linux-x86_64"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
          v.name = name
      #    #v.customize ["modifyvm", :id, "--memory", 200]
      end
    end
  end

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4000"
    vb.cpus = "4"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", run: "always", inline: <<-SHELL
  #   # apply ip address
  #   sudo nmcli connection reload
  #   sudo systemctl restart network
  # SHELL
  config.vm.provision "shell", path: "install-docker.sh"

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo yum install -y ntp
  #   sudo systemctl enable ntpd
  #   sudo systemctl start ntpd
  #   # sudo rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
  #   # sudo yum install -y puppet-agent
  #   # puppet resource service puppet ensure=running enable=true
  #   # puppet module install garethr/docker
  #   # puppet apply -e "include 'docker'"
  #   # install and start docker
  #   sudo yum install -y yum-utils
  #   sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  #   sudo yum -y install docker-ce
  #   sudo systemctl enable docker
  #   sudo systemctl start docker
  #
  #   # install docker-compose
  #   cp docker-compose-Linux-x86_64 /usr/local/bin/docker-compose
  #   chmod +x /usr/local/bin/docker-compose
  # SHELL
end
